spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coderhouse
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  jpa-hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect